The Graph: Add initial subgraph, eaglet deployment script and a few nice things
aragon/govern pull request #8
Opened 2020-10-01 03:49 UTC by Evalir

Adds a very very basic subgraph without the stateless tracking features, but with all barebone entities created and running. You can see it at https://thegraph.com/explorer/subgraph/evalir/aragon-eg-rinkeby-staging?selected=playground .

For compiling and running it yourself, do `yarn manifest-rinkeby-staging` and then `yarn deploy-rinkeby-staging` with your `GRAPHKEY` (access token) set in the `build-manifest.sh` file.

Also adds a simple deployment script for the Eaglet Factory; I've added the etherscan plugin so we can verify just by passing the addresses and setting up an API key. Read more over here: https://buidler.dev/plugins/nomiclabs-buidler-etherscan.html 

Task list:
- [x] ABI Syncing Script
- [x] Track EagletRegistry (?)
- [x] Track Eaglet
- [x] Track OptimisticQueue
- [x] Track Containers (Mainly Action information) (in progress)
- [x] Track dispute rulings (in progress)

2020-10-01 04:32 UTC, izqui requested changes

2020-10-01 04:32 UTC, izqui commented on subgraph/manifest/data/mainnet-staging.json
> +{
clean up

2020-10-01 04:32 UTC, izqui commented on subgraph/manifest/data/mainnet.json
> +{
clean up

2020-10-01 04:32 UTC, izqui commented on subgraph/manifest/data/xdai-staging.json
> +{
clean up

2020-10-01 04:32 UTC, izqui commented on subgraph/manifest/data/xdai.json
> +{
clean up

2020-10-01 04:32 UTC, izqui commented on subgraph/package.json
> +  "name": "@1hive/subgraph-conviction-voting",
name

2020-10-01 04:32 UTC, izqui commented on subgraph/src/ConvictionVoting.ts
> +/* eslint-disable @typescript-eslint/no-use-before-define */
clean up

2020-10-01 04:32 UTC, izqui commented on subgraph/src/aragon-hooks.ts
> +export function getTemplateForApp(appId: string): string | null {
clean up

2020-10-01 04:32 UTC, izqui commented on subgraph/src/aragon/aragon.ts
> +import { Address, DataSourceTemplate } from '@graphprotocol/graph-ts'
clean up

2020-10-01 04:32 UTC, izqui commented on subgraph/src/aragon/mappings/DAOFactory.ts
> +import { DeployDAO as DeployDAOEvent } from "../../../generated/DAOFactory@0.8.1/DAOFactory";
clean up

2020-10-01 04:32 UTC, izqui commented on subgraph/src/aragon/mappings/DAOKit.ts
> +import { DeployInstance as DeployInstanceEvent } from '../../../generated/bare-kit.aragonpm.eth@1.0.0/DAOKit'
clean up

2020-10-01 04:32 UTC, izqui commented on subgraph/src/aragon/mappings/DAOTemplate.ts
> +import { DeployDao as DeployDaoEvent } from '../../../generated/karma-template.aragonpm.eth@1.0.0/DAOTemplate'
clean up

2020-10-01 04:32 UTC, izqui commented on subgraph/abis/Eaglet.json
> +[
I think we should extract this at runtime from `/artifacts`

2020-10-01 23:57 UTC, Evalir commented on subgraph/schema.graphql
> +  config: Config
This is not ideal at all, configs should _never_ be null, but doing this while we settle on the way to create an actual "production" eaglet; ideally we will log the config on `NewEaglet`. We need because The Graph is processing the events in this order:
- `NewEaglet`
- `Configured`

and we create the `OptimisticQueue` entity during `NewEaglet`, so we must leave `config` as null.

2020-10-02 05:35 UTC, Evalir commented on subgraph/abis/Eaglet.json
> +[
Done in https://github.com/aragon/eaglet/pull/8/commits/a7016fea2c35a27a4d4328ef805d897e0e810005

2020-10-06 16:53 UTC, merged